apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: 019496914213.dkr.ecr.us-east-2.amazonaws.com/test-php:latest
        ports:
        - containerPort: 9000
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: php
    name: svc-php
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9000
    selector:
      app: php
    type: ClusterIP

